### ISSUE TITLE
Login doesn't work reliable

### ISSUE THREAD

**Issue by lkiesow** [virtUOS/ai-portal#17]
Tested in Firefox:

1. Click into username form field
2. Let browser/password manager autofill login and password
3. Do *not* click into the login field
4. Click on „Login“
5. Nothing happens. I should be logged in.

Also, not working

1. Fill in username and password
2. While in either field, hit „Enter“
3. Nothing happens. I should be logged in.

**Comment by Odrec** [comment]
This should be fixed now in the latest commit
